<?php
namespace App\SocialMedia\Facades;
use Illuminate\Support\Facades\Facade;


class Facebook extends Facade{
    public static function getFacadeAccessor()
    {
        return "fb";
       // parent::getFacadeAccessor(); // TODO: Change the autogenerated stub
    }
}
?>